<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var Commerce365\Core\Block\Adminhtml\System\Config\Buttons\Sync $block */
?>
<div id="commerce365-configuration-testlogging-wrapper">
     <?= $block->getButtonHtml() ?>
     <div class="indicator" id="commerce365-configuration-testlogging-indicator">

          <img class="check_processing" hidden="hidden" alt="Processing"
               src="<?= $block->getViewFileUrl('images/process_spinner.gif') ?>" />
          <img class="check_success" hidden="hidden" alt="Success"
               src="<?= $block->getViewFileUrl('images/rule_component_apply.gif') ?>" />
          <img class="check_error" hidden="hidden" alt="Error"
               src="<?= $block->getViewFileUrl('images/rule_component_remove.gif') ?>" />
               <span id="test_message_span"></span>
          </div>
</div>
